baseURL = "https://natedean.info/"
languageCode = "en-us"
title = "Nate Dean"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6
GoogleAnalytics = "UA-143772956-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Nate Dean's Website"
  facebook = "https://www.facebook.com/guitarthinker/"
  twitter = "https://twitter.com/GuitarThinker"
  instagram = "https://www.instagram.com/guitarthinker/"
  youtube = "https://www.youtube.com/user/GuitarThinker/"
  github = "https://github.com/natedean"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/background.jpg"
  recent_posts_number = 6
  env = "production"

[[menu.extended]]
    name = "GuitarThinker"
    title = "GuitarThinker.com"
    url = "https://guitarthinker.com"

[caches]
[caches.getjson]
  maxAge = "1h" # set to -1 to bust cache at any time