jobs:
  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: public
          overwrite: true
          to: 's3://natedean'
orbs:
  hugo: circleci/hugo@0.2
  aws-s3: circleci/aws-s3@1.0.15
version: 2.1
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          source: ./
          version: '0.55'
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build