jobs:
  deploy:
    docker:
      - image: cibuilds/base
    steps:
      - attach_workspace:
          at: my-site
      - run: aws s3 cp public/ s3://natedean --recursive
orbs:
  hugo: circleci/hugo@0.2
version: 2.1
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          source: ./
          version: '0.55'
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build